modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="powder_keg" #mandatory
version="1.0.0" #mandatory
displayName="Powder Keg" #mandatory
credits="superlord9362 (code) and weastian (art)" #optional
authors="superlord9362" #optional
description='''
A simple vanilla styled gun mod.
'''
[[dependencies.powder_keg]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.powder_keg]]
    modId="minecraft"
    mandatory=true
	versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
